### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by balouji** [cravisjan97/Deep-Clustering#1]
There is this error 

Traceback (most recent call last):
  File "main_cnn_softmax.py", line 155, in <module>
    ff_output[s[arg,j]]=arg
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by cravisjan97** [comment]
Can you print the array s[:,:] to check if it contains only integers?
